### ISSUE TITLE
Cannot use plugin when using fastify ESM template

### ISSUE THREAD

**Issue by mrlectus** [joggrdocs/fastify-prisma#189]
### Description

Error when using fastify ESM template

### Reproduction

Use fastify cli to generate the app
`fastify generate myapp --lang=ts --esm"`

install this plugin
`npm install @joggr/fastify-prisma`

Add to plugin folder

```typescript
import fp from "fastify-plugin";
import fastifyPrisma from "@joggr/fastify-prisma";

export default fp(async (fastify) => {
  await fastify.register(fastifyPrisma); // This doesnt work, I am get the error no overload match this call
});
```

### Environment

version: 2.2.2

**Comment by zrosenbauer** [comment]
Fixed in #190, upgrade to v3 to get new changes.
